"""empty message

Revision ID: 815650fb6a6e
Revises: 
Create Date: 2021-08-15 02:15:55.199521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815650fb6a6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('author', sa.String(length=80), nullable=False),
    sa.Column('published_date', sa.Date(), nullable=False),
    sa.Column('ISBN', sa.Integer(), nullable=False),
    sa.Column('num_pages', sa.Integer(), nullable=False),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ISBN'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
